### PR TITLE
fixed the output

### PR DESCRIPTION
**Pull request by tristankrass**

### CODE REVIEW

**Comment by hswolff** [comment]
What's this do?

**Comment by tristankrass** [comment]
Hey! Basically now if you export the Json file from the ghost admin it
doesn't come with the markdown included. It comes with html included. I
added a npm package to fix it!
*Parimate soovidega*

*Tristan Krass <http://tristan.biz>*

**Comment by hswolff** [comment]
Sweet! Ty!

**Comment by hswolff** [comment]
Published as 1.3.0.

**Pull request merged**
